---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
      - javascript
  tslint:
    enabled: true
    config: tslint-codeclimate.json
  fixme:
    enabled: false
ratings:
  paths:
  - "**.ts"
exclude_paths:
- test/
- coverage/
- node_modules
