env:
  global:
    - GITHUB_REPO: proustibat/ion-prism
    # generate token at https://github.com/settings/tokens/new
    # generate secure with travis encrypt -r username/repository GH_TOKEN=[the token you created before]

language: node_js
node_js: '8'
cache: npm

# create a user token here: https://sonarcloud.io/account/security
# run `travis encrypt your-token-here`
# paste secure token below
addons:
  sonarcloud:
    organization: proustibat-github
    token:
      secure: "UWJt9HlJjXuKIY/JgkKcRaRUZ7GkqsTmoGmJUEyBkc0lKPGZIucQi8PVZvfS/FFJF4RDArbLy7XR5Jozdl36aeTGvq6EhcX+8SyxhjyGhqg+CEZvirdlqyO07XSbRPQt+IcGU541/sbrQw4/GhonvdPDLOHcsdK1biCndjS7KrDLjSO1gyZHs3x1zm1OYeOhiA0vsTYWefm8LJbCKtgy1ly+V5iKmX7IUAxlfSrTyBkRAdI51BxcEJC8q222Kw4ATnT4lOie2ahsUVZ4mGfI8x/DyujuhKXVc+AN5RHcHUipqCR6EgYCGHOk//3xFMqy6Xt06fGxGt/Tnc5Ogf34U7aFpgQmPAnTeL+c0gHp+HMU5ouIMbYTmC2J4RJfMIe/gCpyoE5RKivmd4QpfAgcjI5ABRQjIpDc+WjghxC97zqv8RUvRIKirbKpvyXW2aMj1UALsoJWZplkZqc5Hseyo/9Sfaw7vCNuNaT5FM2lshAxnKG5ss1AXZx3BtXTAdsy3o5vX5GNWwx565rdVHprJZAodyb5osg3IR3nQNPvLwEOxZRKxGM2Y4p/k8Sl4J7PVQkovvETcQG33ADUB8Eb0evJXpjqgp5A2g0q1pztSKLjNl85/UqK3XNgpc+T8vimzQ4PnjAMG0TyWWkMu7BS9gHDCnYQclBEzQnZ3P49ors="

before_install:

install:
- npm install

script:
- npm run build
- bash sonar.sh

# Here we want to check out where we are.
# We only want to update Github Pages if we're building
# the master branch of the original repository, so we
# have to check $TRAVIS_PULL_REQUEST and $TRAVIS_BRANCH.
# If we are here, we run bash deploy.sh
#after_success:
# - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
